# Generated by Django 4.1 on 2023-03-02 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_newsletterlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsLetterList',
        ),
    ]
