# Generated by Django 4.1 on 2022-08-28 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_category_certifications_supportdocument_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Modules',
            new_name='Module',
        ),
    ]
