# Generated by Django 4.1 on 2023-02-26 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='video',
            field=models.FileField(null=True, upload_to='modules'),
        ),
    ]
