# Generated by Django 4.1 on 2023-02-26 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_module_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='intoduction_video',
            field=models.FileField(null=True, upload_to='intro-vids'),
        ),
    ]
