# Generated by Django 4.1 on 2023-02-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_module_intoduction_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='intoduction_video',
        ),
        migrations.AddField(
            model_name='course',
            name='intoduction_video',
            field=models.FileField(null=True, upload_to='intro-vids'),
        ),
    ]
