# Generated by Django 4.1 on 2023-02-28 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
        ('courses', '0012_module_slug_supportdocument_name_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolement',
            name='payment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolement', to='checkout.payment'),
        ),
        migrations.AddField(
            model_name='enrolement',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'failed'), (1, 'Success'), (2, 'Canceled')], default=0),
        ),
    ]
