# Generated by Django 4.1 on 2023-03-01 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_enrolement_payment_enrolement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolement',
            name='total_amount',
            field=models.FloatField(default=0),
        ),
    ]
