# Generated by Django 4.1 on 2023-03-04 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_coupon_enrolement_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
