# Generated by Django 3.2.13 on 2023-03-05 14:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_supportdocument_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
