# Generated by Django 4.1 on 2023-08-05 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_alter_subcategory_options_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='profession',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
