# Generated by Django 4.1 on 2024-05-13 12:39

import custom_storage.custom_storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_alter_module_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='video',
            field=models.FileField(blank=True, null=True, storage=custom_storage.custom_storages.PrivateMediaStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='supportdocument',
            name='file',
            field=models.FileField(storage=custom_storage.custom_storages.PrivateMediaStorage(), upload_to='course_support_files'),
        ),
    ]
